# Generated by Django 4.1.4 on 2023-01-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="INFORMATION",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "NAME",
                    models.CharField(max_length=22, verbose_name="НАЗВАНИЕ КУРСА: "),
                ),
                ("YEAR", models.CharField(max_length=50, verbose_name="ВОЗРАСТ: ")),
                (
                    "NAME_TEACHER",
                    models.CharField(
                        max_length=100, verbose_name="ФИО ПРЕПОДВАТЕЛЕЙ: "
                    ),
                ),
                ("INFO", models.TextField(max_length=500, verbose_name="О КУРСЕ")),
            ],
        ),
    ]
