# Generated by Django 4.1.4 on 2023-01-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_information_n"),
    ]

    operations = [
        migrations.CreateModel(
            name="USER_REG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NAME", models.CharField(max_length=100, verbose_name="ФИО: ")),
                ("YEAR", models.IntegerField(max_length=50, verbose_name="ВОЗРАСТ: ")),
                (
                    "NUMBER",
                    models.IntegerField(
                        max_length=100, verbose_name="Контактный телефон: "
                    ),
                ),
                (
                    "KURS",
                    models.TextField(max_length=500, verbose_name="Название курса"),
                ),
            ],
        ),
    ]
