# Generated by Django 4.1.4 on 2023-01-03 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_user_reg_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_reg",
            name="USER",
            field=models.CharField(default=1, max_length=100, verbose_name="USER: "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_reg",
            name="NUMBER",
            field=models.CharField(max_length=30, verbose_name="Контактный телефон: "),
        ),
        migrations.AlterField(
            model_name="user_reg",
            name="YEAR",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="ВОЗРАСТ: ",
            ),
        ),
    ]
